### ISSUE TITLE
nice module with great features!

### ISSUE THREAD

**Issue by maheshsetti** [GoIncremental/gi-commerce#3]
Can you people provide some documentation?

**Comment by Bochenski** [comment]
Thanks @maheshsetti

We're busy building out these modules as I type, and when they stabilise we hope to be able to put some time into documenting them for the community.

Let me know if there is anything specific I can help you with.

David

**Comment by maheshsetti** [comment]
Thanks @Bochenski 
Is anyone using this modules for real time application?

can you give quick start?
